# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/themes/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "max-age=60, stale-while-revalidate=604800"
    
[[headers]]
  for = "/theme-parser.js"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "max-age=60, stale-while-revalidate=604800"
    
[[headers]]
  for = "/palette.svg"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "max-age=604800"
    
[[headers]]
  for = "/HUBCHICKEN.png"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "max-age=604800"
    
[[headers]]
  for = "/foolchicken.png"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "max-age=604800"
    
[[headers]]
  for = "/style.css"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "max-age=60, stale-while-revalidate=604800"
    
[[headers]]
  for = "/_cross.html"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "max-age=604800"

